<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rcllean_examples</name>
  <version>0.1.0</version>
  <description>
    Lean 4 ROS 2 nodes built by colcon, using a custom interface package.
  </description>
  <maintainer email="rmatheu@umd.edu">Ryan Matheu</maintainer>
  <license>Apache-2.0</license>


  <depend>rcllean</depend>
  <depend>rcllean_example_interfaces</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>


  <export>
    <build_type>ament_lake</build_type>
  </export>
</package>
